services:
  - type: web
    name: rmas-national
    env: docker
    region: oregon
    buildCommand: docker build -t rmas .
    startCommand: docker run -p 5000:5000 -e PORT=5000 rmas
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: SENDER_EMAIL
        value: nationalrmas@gmail.com
      - key: PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PORT
        value: "5000"
